export const GET_PICTURES = Symbol('GET_PICTURES');
export const GET_PICTURES_START = Symbol('GET_PICTURES_START');
export const GET_PICTURES_SUCCESS = Symbol('GET_PICTURES_SUCCESS');
export const GET_PICTURES_ERROR = Symbol('GET_PICTURES_ERROR');

export const POST_PICTURE = Symbol('POST_PICTURE');
export const POST_PICTURE_START = Symbol('POST_PICTURE_START');
export const POST_PICTURE_SUCCESS = Symbol('POST_PICTURE_SUCCESS');
export const POST_PICTURE_ERROR = Symbol('POST_PICTURE_ERROR');
export const RESET_POST_REQUEST_STATUS = Symbol('RESET_POST_REQUEST_STATUS');
export const SET_ACTIVE_PICTURE = Symbol('SET_ACTIVE_PICTURE');

export const PICTURE_EDITOR_HIDE = Symbol('PICTURE_EDITOR_HIDE');
export const PICTURE_EDITOR_SHOW = Symbol('PICTURE_EDITOR_SHOW');
export const UPLOADING_STATUS = Symbol('UPLOADING_STATUS');

export const SET_PICTURE_SRC = Symbol('SET_PICTURE_SRC');
export const SET_PICTURE_EFFECT = Symbol('SET_PICTURE_EFFECT');
export const SET_PICTURE_EFFECT_LEVEL = Symbol('SET_PICTURE_EFFECT_LEVEL');
export const SET_PICTURE_SCALE = Symbol('SET_PICTURE_SCALE');
export const SET_PICTURE_HASHTAGS = Symbol('SET_PICTURE_HASHTAGS');
export const SET_PICTURE_COMMENT = Symbol('SET_PICTURE_COMMENT');
export const SET_DEFAULT_VALUES = Symbol('SET_DEFAULT_VALUES');
