export const GET_PICTURES = 'GET_PICTURES';
export const GET_PICTURES_START = 'GET_PICTURES_START';
export const GET_PICTURES_SUCCESS = 'GET_PICTURES_SUCCESS';
export const GET_PICTURES_ERROR = 'GET_PICTURES_ERROR';

export const POST_PICTURE = 'POST_PICTURE';
export const FETCH_PICTURE_START = 'FETCH_PICTURE_START';
export const FETCH_PICTURE_SUCCESS = 'FETCH_PICTURE_SUCCESS';
export const FETCH_PICTURE_ERROR = 'FETCH_PICTURE_ERROR';
export const RESET_FETCH_STATUS = 'RESET_FETCH_STATUS';
export const SET_ACTIVE_PICTURE = 'SET_ACTIVE_PICTURE';

export const PICTURE_EDITOR_HIDE = 'PICTURE_EDITOR_HIDE';
export const PICTURE_EDITOR_SHOW = 'PICTURE_EDITOR_SHOW';

export const SET_PICTURE_EFFECT = 'SET_PICTURE_EFFECT';
export const SET_PICTURE_EFFECT_LEVEL = 'SET_PICTURE_EFFECT_LEVEL';
export const SET_PICTURE_SCALE = 'SET_PICTURE_SCALE';
export const SET_PICTURE_HASHTAGS = 'SET_PICTURE_HASHTAGS';
export const SET_PICTURE_COMMENT = 'SET_PICTURE_COMMENT';
export const SET_DEFAULT_VALUES = 'SET_DEFAULT_VALUES';
